/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

plugins {
    java
    id("org.jetbrains.kotlin.jvm").version("1.3.30").apply(false)
}

allprojects {

}

dependencies {
    implementation(project(":sz-tushare"))
    implementation(project(":sz-futu-protocol"))
    implementation(project(":sz-futu-client"))
    implementation(project(":api_server"))
}