/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

plugins {
    java
    id("org.jetbrains.kotlin.jvm").version("1.3.41").apply(false)
}

allprojects {

    repositories {
        // Use jcenter for resolving your dependencies.
        // You can declare any Maven/Ivy/file repository here.
        mavenLocal()
        mavenCentral()
        jcenter()
    }
}

dependencies {
    implementation(project(":sz-tushare"))
    implementation(project(":sz-futu-protocol"))
    implementation(project(":sz-futu-client"))
    implementation(project(":api_server"))
}