/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.3/userguide/multi_project_builds.html
 */

//rootProject.name = "vertx-web-mutli"

include(":sz-tushare")
include(":sz-futu-protocol")
include(":sz-futu-client")
include(":api_server")
include(":tushare-data")
include(":cmd_test")
